# Generated by Django 2.0.4 on 2018-05-03 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_track_ajax', '0002_billitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billitem',
            name='user',
            field=models.ForeignKey(on_delete=True, related_name='bills_of', to='login_reg.User'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
